<?php


use Drupal\Core\Form\FormStateInterface;

/**
 * Impement hook_theme().
 */
function legalgen_theme($existing, $type, $theme, $path){
  return [
    'impressum_template' => [
      'variables' => [
        'wisski_url'             => NULL,
        'project_name'           => NULL,
        'publisher_institution'  => NULL,
        'publisher_institute'    => NULL,
        'publisher_name'         => NULL,
        'publisher_address'      => NULL,
        'publisher_plz'          => NULL,
        'publisher_city'         => NULL,
        'publisher_email'        => NULL,
        'custom_legal_form'      => NULL,
        'contact_name'           => NULL,
        'contact_phone'          => NULL,
        'contact_email'          => NULL,
        'support_institute'      => NULL,
        'support_url'            => NULL,
        'support_email'          => NULL,
        'support_staff_array'    => NULL,
        'authority_name'         => NULL,
        'authority_address'      => NULL,
        'authority_plz'          => NULL,
        'authority_city'         => NULL,
        'authority_url'          => NULL,
        'id_vat'                 => NULL,
        'id_tax'                 => NULL,
        'id_duns'                => NULL,
        'id_eori'                => NULL,
        'licence_title'          => NULL,
        'licence_url'            => NULL,
        'uses_fau_design'        => NULL,
        'custom_licence_txt'     => NULL,
        'no_default_txt'         => NULL,
        'custom_exclusion'       => NULL,
        'hide_disclaimer'        => NULL,
        'custom_disclaimer'      => NULL,
        'date'                   => NULL,
        ],
    ],


    'legalnotice_template' => [
      'variables' => [
        'wisski_url'             => NULL,
        'project_name'           => NULL,
        'publisher_institution'  => NULL,
        'publisher_institute'    => NULL,
        'publisher_name'         => NULL,
        'publisher_address'      => NULL,
        'publisher_plz'          => NULL,
        'publisher_city'         => NULL,
        'publisher_email'        => NULL,
        'custom_legal_form'      => NULL,
        'contact_name'           => NULL,
        'contact_phone'          => NULL,
        'contact_email'          => NULL,
        'support_institute'      => NULL,
        'support_url'            => NULL,
        'support_email'          => NULL,
        'support_staff_array'    => NULL,
        'authority_name'         => NULL,
        'authority_address'      => NULL,
        'authority_plz'          => NULL,
        'authority_city'         => NULL,
        'authority_url'          => NULL,
        'id_vat'                 => NULL,
        'id_tax'                 => NULL,
        'id_duns'                => NULL,
        'id_eori'                => NULL,
        'licence_title'          => NULL,
        'licence_url'            => NULL,
        'uses_fau_design'        => NULL,
        'custom_licence_txt'     => NULL,
        'no_default_txt'         => NULL,
        'custom_exclusion'       => NULL,
        'hide_disclaimer'        => NULL,
        'custom_disclaimer'      => NULL,
        'date'                   => NULL,
        ],
    ],


    'barrierefreiheit_template' => [
      'variables' => [
        'wisski_url'                   => NULL,
        'status'                       => NULL,
        'methodology'                  => NULL,
        'creation_date'                => NULL,
        'last_revision_date'           => NULL,
        'report_url'                   => NULL,
        'known_issues'                 => NULL,
        'issues_array'                 => NULL,
        'justification'                => NULL,
        'justification_array'          => NULL,
        'alternatives'                 => NULL,
        'alternatives_array'           => NULL,
        'contact_accessibility_name'   => NULL,
        'contact_accessibility_phone'  => NULL,
        'contact_accessibility_email'  => NULL,
        'support_institute'            => NULL,
        'support_url'                  => NULL,
        'support_address'              => NULL,
        'support_plz'                  => NULL,
        'support_city'                 => NULL,
        'support_email'                => NULL,
        'oversight_name'               => NULL,
        'oversight_dept'               => NULL,
        'oversight_address'            => NULL,
        'oversight_plz'                => NULL,
        'oversight_city'               => NULL,
        'oversight_phone'              => NULL,
        'oversight_email'              => NULL,
        'oversight_url'                => NULL,
        'date'                         => NULL,
        ],
    ],

    'accessibility_template' => [
      'variables' => [
        'wisski_url'                    => NULL,
        'status'                        => NULL,
        'methodology'                   => NULL,
        'creation_date'                 => NULL,
        'last_revision_date'            => NULL,
        'report_url'                    => NULL,
        'known_issues'                  => NULL,
        'issues_array'                  => NULL,
        'justification'                 => NULL,
        'justification_array'           => NULL,
        'alternatives'                  => NULL,
        'alternatives_array'            => NULL,
        'contact_accessibility_name'    => NULL,
        'contact_accessibility_phone'   => NULL,
        'contact_accessibility_email'   => NULL,
        'support_institute'             => NULL,
        'support_url'                   => NULL,
        'support_address'               => NULL,
        'support_plz'                   => NULL,
        'support_city'                  => NULL,
        'support_email'                 => NULL,
        'oversight_name'                => NULL,
        'oversight_dept'                => NULL,
        'oversight_address'             => NULL,
        'oversight_plz'                 => NULL,
        'oversight_city'                => NULL,
        'oversight_phone'               => NULL,
        'oversight_email'               => NULL,
        'oversight_url'                 => NULL,
        'date'                          => NULL,
        ],
    ],


    'datenschutz_template' => [
      'variables' => [
        'not_fau'                                    => NULL,
        'legal_notice_url'                           => NULL,
        'security_official_title'                    => NULL,
        'security_official_name'                     => NULL,
        'security_official_add'                      => NULL,
        'security_official_address'                  => NULL,
        'security_official_plz'                      => NULL,
        'security_official_city'                     => NULL,
        'security_official_phone'                    => NULL,
        'security_official_fax'                      => NULL,
        'security_official_email'                    => NULL,
        'third_service_provider'                     => NULL,
        'third_service_description_data_collection'  => NULL,
        'third_service_legal_basis_data_collection'  => NULL,
        'third_service_objection_data_collection'    => NULL,
        'data_commissioner_title'                    => NULL,
        'data_commissioner_address'                  => NULL,
        'data_commissioner_plz'                      => NULL,
        'data_commissioner_city'                     => NULL,
        'date'                    	                 => NULL,
        ],
    ],

    'privacy_template' => [
      'variables' => [
        'not_fau'                                    => NULL,
        'legal_notice_url'                           => NULL,
        'security_official_title'                    => NULL,
        'security_official_name'                     => NULL,
        'security_official_add'                      => NULL,
        'security_official_address'                  => NULL,
        'security_official_plz'                      => NULL,
        'security_official_city'                     => NULL,
        'security_official_phone'                    => NULL,
        'security_official_fax'                      => NULL,
        'security_official_email'                    => NULL,
        'third_service_provider'                     => NULL,
        'third_service_description_data_collection'  => NULL,
        'third_service_legal_basis_data_collection'  => NULL,
        'third_service_objection_data_collection'    => NULL,
        'data_commissioner_title'                    => NULL,
        'data_commissioner_address'                  => NULL,
        'data_commissioner_plz'                      => NULL,
        'data_commissioner_city'                     => NULL,
        'date'                                       => NULL,
        ],
    ],
  ];
}


/**
 * Implements hook_form_alter().
 * Attaches Library to Pages
 */
function legalgen_page_attachments(array &$page) {
  if (!\Drupal::currentUser()->hasPermission('access contextual links')) {
    return;
  }

  $page['#attached']['library'][] = 'legalgen/legalpages_library';
}


/**
 * Implements hook_form_alter().
 * Attaches Library to Form
 */
function legalgen_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $formObject = $form_state->getFormObject();

  if ($formObject instanceof FormStateInterface) {

    // CHECK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    $entity= $formObject->FieldItemListInterface::getEntity();

    if ($entity->getEntityTypeId() === 'node' && in_array($entity->bundle(), ['organisation', 'location', 'event', 'article'])) {

      $form['#attached']['library'][] = 'legalgen/legalpages_library';
    }
  }
}

/**
 * Implements hook_form_alter().
 * To Display Dialogs
 */
function mymodule_preprocess_node__page(array &$variables) : void {
	// Module name: 'mymodule', library name: 'mymodule'.
	$variables['#attached']['library'][] = 'legalgen/legalpages_library';
}